// Generated by CoffeeScript 1.7.1
(function() {
  var libs;

  libs = ['angular', '../app', 'services/api'];

  define(libs, function(angular, app) {
    var project;
    project = function(api) {
      return {
        restrict: 'E',
        scope: {
          model: '='
        },
        replace: true,
        templateUrl: '/_/views/_project.html',
        link: function(scope, elem, attrs) {
          scope.select = function() {
            return api.project.select(scope.model.path).then(function(data) {
              return scope.$root.loadProjects();
            });
          };
          return scope.remove = function($event) {
            api.project.remove(scope.model.path).then(function() {
              return scope.$root.loadProjects();
            });
            $event.stopPropagation();
            return $event.preventDefault();
          };
        }
      };
    };
    return app.directive('project', project);
  });

}).call(this);
