// Generated by CoffeeScript 1.7.1
(function() {
  var libs, main;

  libs = ['underscore', 'angular', 'ngRoute', 'mgcrea.ngStrap', 'services/api', 'controllers/IndexController', 'controllers/FilesController', 'controllers/SettingsController', 'directives/project'];

  main = function(_, angular) {
    var index;
    index = angular.module('index', ['ngRoute', 'mgcrea.ngStrap', 'app']);
    index.run(function(api) {
      return console.log('run');
    });
    return angular.element(document).ready(function() {
      console.log('ready');
      return angular.bootstrap(document, ['index']);
    });
  };

  require(['/_/js/config.js'], function() {
    return require(libs, main);
  });

}).call(this);
