// Generated by CoffeeScript 1.6.3
(function() {
  var FileModel, FolderSegment, ProjectModel, ViewModel, joinPath,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    _this = this;

  joinPath = function(p1, p2) {
    var path;
    path = [p1, p2].join('/');
    return path = path.replace(/\/+/g, '/');
  };

  FileModel = function(data, project) {
    var _this = this;
    this.name = ko.observable(data['name']);
    this.type = ko.observable(data['type']);
    this.absolutePath = ko.observable(data['absolutePath']);
    this.relativePath = ko.computed(function() {
      var relPath;
      relPath = _this.absolutePath().replace(project.path(), '');
      if (relPath && relPath[0] === '/') {
        return relPath = relPath.substr(1);
      }
    });
    this.url = ko.computed(function() {
      var root;
      root = project.root;
      if (root.port()) {
        return "http://" + (project.activeDomain()) + ":" + (root.port()) + "/" + (_this.relativePath());
      } else {
        return "http://" + (project.activeDomain()) + "/" + (_this.relativePath());
      }
    });
    this.isMuted = ko.computed(function() {
      var mutePath, _i, _len, _ref;
      if (!project.muteList()) {
        false;
      }
      _ref = project.muteList();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        mutePath = _ref[_i];
        if (_this.absolutePath() === joinPath(project.path(), mutePath)) {
          true;
        }
      }
      return false;
    });
    this.mute = function() {
      var _ref;
      if (_ref = _this.relativePath(), __indexOf.call(project.muteList(), _ref) < 0) {
        project.muteList.push(_this.relativePath());
        return project.save();
      }
    };
    this.unmute = function() {
      var _ref;
      if (_ref = _this.relativePath(), __indexOf.call(project.muteList(), _ref) >= 0) {
        project.muteList.remove(_this.relativepath());
        return project.save();
      }
    };
    this.onClick = function() {
      if (_this.type() === 'DIR') {
        project.currentFolder(_this.relativePath());
        false;
      }
      return true;
    };
    return this;
  };

  FolderSegment = function(name, relativePath, project) {
    var _this = this;
    this.name = ko.observable(name);
    this.relativePath = ko.observable(relativePath);
    this.onClick = function() {
      return project.currentFolder(_this.relativePath());
    };
    return this;
  };

  ProjectModel = function(data, root) {
    var _this = this;
    this.root = root;
    this.path = ko.observable("");
    this.active = ko.observable(false);
    this.muteList = ko.observableArray([]);
    this.targetHost = ko.observable('');
    this.domains = ko.observableArray([]);
    this.activeDomain = ko.observable('127.0.0.1');
    this.activeDomains = ko.observableArray(['127.0.0.1']);
    this.activeDomains.subscribe(function(newValue) {
      _this.activeDomain(newValue[0]);
      setTimeout(_this.save, 100);
      return _this.QRCodeFile(_this.QRCodeFile());
    });
    this.allHosts = ko.computed(function() {
      return _this.domains().concat(root.localHosts());
    });
    this.activeDomainAndPort = ko.computed(function() {
      if (root.port()) {
        return "" + (_this.activeDomain()) + ":" + (root.port());
      } else {
        return _this.activeDomain();
      }
    });
    this.clickAddDomain = function(item, event) {
      var domain;
      domain = $.trim(prompt('请输入想要添加的域名：'));
      if (domainf) {
        if (!/^[\w\.\-]+$/.exec(domain)) {
          return alert('格式不对吧');
        } else {
          if (__indexOf.call(_this.omains, domain) >= 0) {
            return alert('域名已存在');
          } else {
            _this.domains.unshift(domain);
            return _this.activeDomains([domain]);
          }
        }
      }
    };
    this.clickRemoveDomain = function(item, event) {
      _this.domains.remove(_this.activeDomain());
      if (_this.activeHosts().length) {
        return _this.activeDomains([_this.allHosts()[0]]);
      }
    };
    this.showSettings = ko.observable($.cookie('hideSettings') !== 'true');
    this.showSettings.subscribe(function(newValue) {
      return $.cookie('hideSettings', !newValue);
    });
    this.submitTargetHost = function(item, event) {
      var targetHost;
      targetHost = $.trim($('#target-host-input').val());
      if (!targetHost) {
        return _this.clearTargetHost();
      } else if (/^[\w\.:\-]+$/.exec(targetHost)) {
        _this.targetHost(targetHost);
        return _this.save();
      } else {
        alert("请输入域名或ip地址（不带协议和路径）和端口，如：\n127.0.0.1:8080\n192.168.0.101\ndomain.com:8080\nmysite.com");
        return $('#target-host-input').val(targetHost).focus().select();
      }
    };
    this.clearTargetHost = function(item, event) {
      _this.targetHost("");
      $('#target-host-input').val("");
      return _this.save();
    };
    this.files = ko.observableArray([]);
    this.folderSegments = ko.observableArray([]);
    this.currentFolder = ko.observable('');
    this.currentFolder.subscribe(function(relativePath) {
      var part, parts, relativeParts, _i, _len;
      _this.folderSegments.removeAll();
      parts = relativePath.split('/');
      relativeParts = [];
      for (_i = 0, _len = parts.length; _i < _len; _i++) {
        part = parts[_i];
        relativeParts.push(part);
        if (part) {
          _this.folderSegments.push(new FolderSegment(part, relativeParts.join('/'), _this));
        }
      }
      return _this.queryFileList(joinPath(_this.path(), relativePath));
    });
    this.currentFolder.extend({
      notify: 'always'
    });
    this.goRoot = function() {
      return this.currentFolder('');
    };
    this.queryFileList = function(path) {
      var _this = this;
      this.files.removeAll();
      return API.os.listDir(path, function(data) {
        var fileData, _i, _len, _ref;
        _this.files.removeAll();
        _ref = data['list'];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          fileData = _ref[_i];
          _this.files.push(new FileModel(fileData, _this));
        }
        return $('#file-list td.op a').tooltip();
      });
    };
    this.QRCodeFile = ko.observable(null);
    this.QRCodeFile.extend({
      notify: 'always'
    });
    this.QRCodeFile.subscribe(function(newValue) {
      if (newValue) {
        $('#qrcode-modal').modal().on('hidden', function() {
          return _this.QRCodeFile(null);
        });
        return _this.updateQRCode(newValue.url());
      }
    });
    this.QRUrlChange = function(item, event) {
      return _this.updateQRCode($(event.target).val());
    };
    this.updateQRCode = function(text) {
      var $el;
      $el = $('#qrcode');
      return $el.empty().qrcode({
        width: $el.width(),
        height: $el.height(),
        text: text
      });
    };
    this.showQRCode = function(item, event) {
      return this.QRCodeFile(item);
    };
    this.load = function(data) {
      _this.path(data.path);
      _this.active((data.active != null) || false);
      _this.muteList(data.muteList || []);
      _this.targetHost(data.targetHost || "");
      _this.domains(data.domains || []);
      _this.activeDomain(data.activeDomain || '127.0.0.1');
      return _this.activeDomains([_this.activeDomain()]);
    };
    this.save = function() {
      return API.project.update(_this);
    };
    this["export"] = function() {
      return {
        path: _this.path(),
        active: _this.active(),
        muteList: _this.muteList(),
        targetHost: _this.targetHost(),
        domains: _this.domains(),
        activeDomain: _this.activeDomain()
      };
    };
    if (data) {
      this.load(data);
    }
    return this;
  };

  ViewModel = function() {
    var _this = this;
    this.port = ko.observable(location.port);
    this.localHosts = ko.observableArray(['127.0.0.1']);
    this.projects = ko.observableArray([]);
    this.projects.subscribe(function(newValue) {
      return setTimeout(function() {
        return $('#projects .op a').tooltip();
      }, 500);
    });
    this.activeProject = ko.observable(null);
    this.activeProject.subscribe(function(project) {
      var _i, _len, _project, _ref;
      if (project) {
        if (!project.active()) {
          project.active(true);
          project.save();
        }
        if (!project.files().length) {
          project.currentFolder('');
        }
      }
      _ref = _this.projects();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _project = _ref[_i];
        if (_project && _project !== project && _project.active()) {
          _project.active(false);
          _project.save();
        }
      }
      return setTimeout(function() {
        return $('#project [data-toggle=tooltip]').tooltip();
      }, 500);
    });
    this.queryLocalHosts = function() {
      return API.os.localHosts(function(resp) {
        return _this.localHosts(resp.hosts);
      });
    };
    this.findProject = function(path) {
      var project, _i, _len, _ref;
      _ref = _this.projects();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        project = _ref[_i];
        if (project.path() === path) {
          return project;
        }
      }
    };
    this.loadProjectData = function(projectData) {
      var project;
      project = _this.findProject(projectData.path);
      if (project) {
        project.load(projectData);
      } else {
        project = new ProjectModel(projectData, _this);
        _this.projects.push(project);
      }
      return project;
    };
    this.queryProjects = function() {
      return API.project.list(function(data) {
        var project, projectData, _i, _len, _ref, _results;
        _ref = data['projects'];
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          projectData = _ref[_i];
          project = _this.loadProjectData(projectData);
          if (project.active() && project !== _this.activeProject()) {
            _results.push(_this.activeProject(project));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
    };
    this.removeProject = function(project) {
      _this.projects.remove(project);
      API.project.remove(project.path());
      if (_this.activeProject() === project) {
        return _this.activeProject(null);
      }
    };
    this.addProjectWithPath = function(path) {
      return API.project.add(path, function(resp) {
        _this.loadProjectData(resp.project);
        if (_this.projects().length === 1 && !_this.activeProject()) {
          _this.activeProject(_this.projects()[0]);
        }
        return $('#new-path-input').val('');
      });
    };
    this.onSelectProject = function(project) {
      return _this.activeProject(project);
    };
    this.askRemoveProject = function(project) {
      if (confirm('是否确认【删除】该项目?')) {
        return _this.removeProject(project);
      }
    };
    this.onSubmitProjectPath = function(formElement) {
      var $input, projectPath;
      $input = $('#new-path-input');
      projectPath = $.trim($input.val());
      $input.val(projectPath);
      if (projectPath) {
        return _this.addProjectWithPath(projectPath);
      } else {
        return alert('请输入路径');
      }
    };
    this.queryLocalHosts();
    this.queryProjects();
    return this;
  };

  $(function() {
    window.vm = new ViewModel();
    ko.applyBindings(vm);
    API.os.f5Version(function(resp) {
      if (resp.status === 'ok') {
        return $.getScript("http://www.getf5.com/update.js?ver=" + resp.version);
      }
    });
    
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ;
    ga('create', 'UA-22253493-9', '127.0.0.1');
    return ga('send', 'pageview');
  });

}).call(this);
