// Generated by CoffeeScript 1.7.1
(function() {
  var libs;

  libs = ['angular', '../app', 'services/api'];

  define(libs, function(angular, app) {
    var FilesController;
    FilesController = function($log, $rootScope, $scope, api) {
      $scope.rootPath = '';
      $scope.relativePath = '';
      $scope.levels = [];
      $scope.list = [];
      $scope.queryList = function() {
        var path;
        path = [$scope.rootPath, $scope.relativePath].join('/');
        if (path) {
          return api.fs.list(path).then(function(data) {
            return $scope.list = data;
          });
        }
      };
      $scope.setRootPath = function(path) {
        $log.debug('rootPath', path);
        if (path === $scope.rootPath) {
          return;
        }
        $scope.rootPath = path;
        $scope.setRelativePath('');
        $scope.list = [];
        return $scope.queryList();
      };
      $scope.setRelativePath = function(path) {
        var level, name, names, _i, _len, _ref;
        $scope.relativePath = path;
        $scope.levels = [];
        names = [];
        _ref = path.split('/');
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          name = _ref[_i];
          if (!name) {
            continue;
          }
          names.push(name);
          level = {
            name: name,
            relativePath: names.join('/')
          };
          $scope.levels.push(level);
        }
        return $scope.queryList();
      };
      $scope.click = function(item) {
        if (item.type === 'DIR') {
          return $scope.setRelativePath([$scope.relativePath, item.name].join('/'));
        } else {
          return window.open("" + $scope.relativePath + "/" + item.name, '_blank');
        }
      };
      return $rootScope.$watch('projects', function(newValue, oldValue) {
        var project, _i, _len, _results;
        if (!newValue || newValue.length === 0) {
          $scope.setRootPath("");
        }
        _results = [];
        for (_i = 0, _len = newValue.length; _i < _len; _i++) {
          project = newValue[_i];
          if (project.active) {
            $scope.setRootPath(project.path);
            break;
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }, true);
    };
    return app.controller('FilesController', FilesController);
  });

}).call(this);
