// Generated by CoffeeScript 1.7.1
(function() {
  var libs;

  libs = ['angular', '../app', 'services/api'];

  define(libs, function(angular, app) {
    var IndexController;
    IndexController = function($rootScope, $scope, api) {
      $rootScope.projects = [];
      $rootScope.loadProjects = function() {
        return api.project.list().then(function(data) {
          return $rootScope.projects = data;
        });
      };
      $scope.newProject = {
        path: ''
      };
      $scope.addProject = function(path) {
        return api.project.add(path).then(function() {
          $scope.newProject.path = '';
          return $rootScope.loadProjects();
        });
      };
      return $rootScope.loadProjects();
    };
    return app.controller('IndexController', IndexController);
  });

}).call(this);
