// Generated by CoffeeScript 1.7.1
(function() {
  var libs;

  libs = ['angular', '../app'];

  define(libs, function(angular, app) {
    var api;
    api = function($http) {
      var API_URL, query;
      API_URL = '/_/api/';
      query = function(cmd, params) {
        if (params == null) {
          params = {};
        }
        return $http.get(API_URL + cmd, {
          params: params
        });
      };
      return {
        os: {
          f5Version: function() {
            return query('os/f5Version');
          },
          listDir: function(path) {
            return query('os/listDir', {
              path: path
            });
          },
          writeFile: function(path, content) {
            return query('os/writeFile', {
              path: path,
              content: content
            });
          },
          localHosts: function() {
            return query('os/localHosts');
          }
        },
        project: {
          list: function() {
            return query('project/list');
          },
          add: function(projectPath) {
            return query('project/add', {
              path: projectPath
            });
          },
          remove: function(projectPath) {
            return query('project/remove', {
              path: projectPath
            });
          },
          update: function(projectPath, options) {
            return query('project/update', {
              path: projectPath,
              options: options
            });
          }
        }
      };
    };
    return app.factory('api', api);
  });

}).call(this);
