// Generated by CoffeeScript 1.7.1
(function() {
  var libs;

  libs = ['angular', '../app'];

  define(libs, function(angular, app) {
    var api;
    api = function($http, $q, $log) {
      var API_URL, query;
      API_URL = '/_/api/';
      query = function(cmd, params) {
        var deferred;
        if (params == null) {
          params = {};
        }
        deferred = $q.defer();
        $http.post(API_URL + cmd, params).then(function(resp) {
          if (resp.status !== 200) {
            $log.error(cmd, params, '->', resp);
            deferred.reject("HTTP ERROR: " + resp.status);
            return alert("HTTP ERROR: " + resp.status);
          } else if (resp.data.error) {
            $log.error(cmd, params, '->', resp);
            deferred.reject(resp.data.error);
            return alert(resp.data.error);
          } else {
            return deferred.resolve(resp.data);
          }
        }, function(resp) {
          $log.error(cmd, params, '->', resp);
          deferred.reject("HTTP ERROR: " + resp.status);
          return alert("HTTP ERROR: " + resp.status);
        });
        return deferred.promise;
      };
      return {
        app: {
          ver: function() {
            return query('app/ver');
          }
        },
        fs: {
          list: function(path) {
            return query('fs/list', {
              path: path
            });
          },
          save: function(path, content) {
            return query('fs/save', {
              path: path,
              content: content
            });
          }
        },
        project: {
          list: function() {
            return query('project/list');
          },
          add: function(projectPath) {
            return query('project/add', {
              path: projectPath
            });
          },
          select: function(projectPath) {
            return query('project/select', {
              path: projectPath
            });
          },
          remove: function(projectPath) {
            return query('project/remove', {
              path: projectPath
            });
          },
          update: function(projectPath, options) {
            return query('project/update', {
              path: projectPath,
              options: options
            });
          }
        }
      };
    };
    return app.factory('api', api);
  });

}).call(this);
